[theme]
primaryColor = "#2563EB"            # Professional Blue
backgroundColor = "#F8FAFC"         # Light Background
secondaryBackgroundColor = "#FFFFFF" # Card Background
textColor = "#1E293B"               # Primary Text
font = "sans serif"




[server]
headless = true
port = 8501